//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmSpaceTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmSpaceTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDP actions translation.
        /// </summary>
        public static string IDPTranslationCaption {
            get {
                return ResourceManager.GetString("IDPTranslationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobMap Batch Upload.
        /// </summary>
        public static string JobMapBatchUploadCaption {
            get {
                return ResourceManager.GetString("JobMapBatchUploadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0} JobMap validity....
        /// </summary>
        public static string JobMapCheckValidity {
            get {
                return ResourceManager.GetString("JobMapCheckValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating uploading.
        /// </summary>
        public static string JobMapInitiatingUploading {
            get {
                return ResourceManager.GetString("JobMapInitiatingUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        public static string JobMapUploadComplete {
            get {
                return ResourceManager.GetString("JobMapUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete. Looks like some issues appeared during uploading. Please check report file in report folder to discover.
        /// </summary>
        public static string JobMapUploadCompleteWithIssues {
            get {
                return ResourceManager.GetString("JobMapUploadCompleteWithIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is empty or contains errors.
        /// </summary>
        public static string JobMapUploadFileIncorrect {
            get {
                return ResourceManager.GetString("JobMapUploadFileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading JobMap: {0}....
        /// </summary>
        public static string JobMapUploading {
            get {
                return ResourceManager.GetString("JobMapUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using Your AmSpace credentials.
        /// </summary>
        public static string LoginButtonToolTip {
            get {
                return ResourceManager.GetString("LoginButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginCaption {
            get {
                return ResourceManager.GetString("LoginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from account.
        /// </summary>
        public static string LogOutToolTip {
            get {
                return ResourceManager.GetString("LogOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileButtonToolTip {
            get {
                return ResourceManager.GetString("OpenFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Structure Management.
        /// </summary>
        public static string OrgStructureCaption {
            get {
                return ResourceManager.GetString("OrgStructureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordBoxToolTip {
            get {
                return ResourceManager.GetString("PasswordBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Batch Upload.
        /// </summary>
        public static string PeopleBatchUploadCaption {
            get {
                return ResourceManager.GetString("PeopleBatchUploadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!{0}Contracts uploaded: {1}.
        /// </summary>
        public static string PeopleUploadFinishUploadMessage {
            get {
                return ResourceManager.GetString("PeopleUploadFinishUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating structure tree....
        /// </summary>
        public static string PeopleUploadGenerateStructureTreeMessage {
            get {
                return ResourceManager.GetString("PeopleUploadGenerateStructureTreeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager for {0} {1} not found!.
        /// </summary>
        public static string PeopleUploadManagerNotFoundMessage {
            get {
                return ResourceManager.GetString("PeopleUploadManagerNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager for {0} {1} not set.
        /// </summary>
        public static string PeopleUploadManagerNotSetMessage {
            get {
                return ResourceManager.GetString("PeopleUploadManagerNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those MPKs are missing:.
        /// </summary>
        public static string PeopleUploadMissingMpkMessage {
            get {
                return ResourceManager.GetString("PeopleUploadMissingMpkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ID:[{2}] done.
        /// </summary>
        public static string PeopleUploadReportUploadStatusMessage {
            get {
                return ResourceManager.GetString("PeopleUploadReportUploadStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating domains....
        /// </summary>
        public static string PeopleUploadValidateDomainMessage {
            get {
                return ResourceManager.GetString("PeopleUploadValidateDomainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports folder.
        /// </summary>
        public static string ReportsFolder {
            get {
                return ResourceManager.GetString("ReportsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select system environment.
        /// </summary>
        public static string SelectEnvironmentToolTip {
            get {
                return ResourceManager.GetString("SelectEnvironmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to AmSpace.
        /// </summary>
        public static string UploadToAmSpaceButtonToolTip {
            get {
                return ResourceManager.GetString("UploadToAmSpaceButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserNameBoxToolTip {
            get {
                return ResourceManager.GetString("UserNameBoxToolTip", resourceCulture);
            }
        }
    }
}
